DEFAULT_TARGET_COUNTRY_ADJECTIVE = "Korean"
DEFAULT_TARGET_COUNTRY_NAME = "South Korea"
DEFAULT_TARGET_MARKET_REGION = "KR"
DEFAULT_CONTENT_TIMEZONE = "Asia/Seoul"

DEFAULT_REGIONS = [
    DEFAULT_TARGET_MARKET_REGION
]

DEFAULT_LIMIT = 20
DEFAULT_SLEEP_SEC = 10.0
DEFAULT_TREND_METHOD = "trending_searches"
DEFAULT_TREND_SOURCE = "rss"
DEFAULT_CSV_HOURS = 4
DEFAULT_CSV_SORT_BY = "traffic"
DEFAULT_FALLBACK_CATEGORY = "stocks"
DEFAULT_FALLBACK_TAGS = ["topic"]
DEFAULT_RSS_INCLUDE_IMAGES = True
DEFAULT_RSS_INCLUDE_ARTICLES = True
DEFAULT_RSS_MAX_ARTICLES_PER_TREND = 10
DEFAULT_RSS_CACHE = True
